apiVersion: apps/v1
kind: Deployment
metadata:
  name: coll-cd46c1f9c3404a56a0577ddbd6a0f14d-depl
  labels:
    app: coll-cd46c1f9c3404a56a0577ddbd6a0f14d
    release: prometheus  # Added label for PodMonitor discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coll-cd46c1f9c3404a56a0577ddbd6a0f14d
      release: prometheus  # Added label for PodMonitor discovery
  template:
    metadata:
      labels:
        app: coll-cd46c1f9c3404a56a0577ddbd6a0f14d
        release: prometheus  # Added label for PodMonitor discovery
    spec:
      containers:
        - name: coll-cd46c1f9c3404a56a0577ddbd6a0f14d
          image: 216084506783.dkr.ecr.ap-south-1.amazonaws.com/backstract_apps:coll-cd46c1f9c3404a56a0577ddbd6a0f14d
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              name: http  # Optional for HTTP traffic
            - containerPort: 7070 #same as the deployed code
              name: metrics  # Added port for metrics scraping