apiVersion: v1
kind: Service
metadata:
  name: coll-cd46c1f9c3404a56a0577ddbd6a0f14d-srv
spec:
  selector:
    app: coll-cd46c1f9c3404a56a0577ddbd6a0f14d
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: ClusterIP